### ISSUE TITLE
두섭리뷰

### ISSUE THREAD

**Issue by dooseopkim** [2hw/DSWeb#1]
1. button으로 된 네비게이션 바가 작동하지 않습니다. button태그 안에 a태그를 추가하시거나,  
button기능을 자바스크립트로 구현하셔야 할 것 같습니다!   
&nbsp;  
2. 자기소개.html에서는 footer가 section의 내용 중간에 나타납니다. 각각 위치를 수정해주셔야 할 것 같아요~  
&nbsp;  
3. 
```css
body div{
  background-color: white;
}
```
속성 때문에 body에 있는 모든 div가 흰 배경색으로 보입니다.  의도하시지는 않은 것 같습니다.   
body > div 로 바꾸시면 header, section, footer만 적용됩니다!
